version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18080:8080"
      - "18443:8443"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/room_rental_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY_STORE: "/app/keystore.p12"
      SERVER_SSL_KEY_STORE_PASSWORD: yourkeystorepassword
      SERVER_SSL_KEY_STORE_TYPE: "PKCS12"
      SERVER_PORT: 8443
    volumes:
      - ./keystore.p12:/app/keystore.p12:ro
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "18081:80"
    depends_on:
      - app
    restart: unless-stopped