spring.application.name=Room-Rental-Service
server.port=7777
spring.datasource.url=jdbc:postgresql://localhost:5432/room_rental_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.bikalp.roomrentalservice.mapper=DEBUG
mybatis.mapper-locations=classpath*:mapper/*.xml
# Validation for images of property
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
app.upload.property-images-dir=uploads/property-images/

# eSewa Test Credentials
esewa.merchant-id=EPAYTEST
esewa.secret-key=8gBm/:&EnhH.1/q
esewa.urls.form=https://rc-epay.esewa.com.np/api/epay/main/v2/form
esewa.urls.status=https://rc.esewa.com.np/api/epay/transaction/status/

# these are the pages that are render after payment based on transaction
#esewa.urls.success-callback=https://developer.esewa.com.np/success
#esewa.urls.failure-callback=https://developer.esewa.com.np/failure

# these are the custom pages that are render after payment based on transaction
esewa.urls.success-callback=http://localhost:3000/payment-success
esewa.urls.failure-callback=http://localhost:3000/payment-failure

# default things that are used during dummy payments
esewa.id1=9806800001
esewa.id2=9806800002
esewa.id3=9806800003
esewa.id4=9806800004
esewa.id5=9806800005
esewa.password=Nepal@123
esewa.mpin=1122
esewa.token=123456

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=official.room.rental@gmail.com
spring.mail.password=zntf xzjm ahcq kcgf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Application Configuration
app.base-url=http://localhost:8080

# cloudinary for property image handling
cloudinary.cloud-name=dcsrqvurv
cloudinary.api-key=856241443262171
cloudinary.api-secret=YI4c802XC6eu0yxnpL-nor30VEY