spring.application.name=Room-Rental-Service
server.port=7777

spring.datasource.url=jdbc:postgresql://localhost:5432/room_rental_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.bikalp.roomrentalservice.mapper=DEBUG
mybatis.mapper-locations=classpath*:mapper/*.xml

# Validation for images of property
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# eSewa Test Credentials
esewa.merchant_id=EPAYTEST
esewa.secret_key=8gBm/:&EnhH.1/q
esewa.client_id=JB0BBQ4aD0UqIThFJwAKBgAXEUkEGQUBBAwdOgABHD4DChwUAB0R
esewa.client_secret=BhwIWQQADhIYSxILExMcAgFXFhcOBwAKBgAXEQ==
esewa.base_url=https://uat.esewa.com.np


# default things that are used during dummy payments
esewa.id=9806800001/2/3/4/5
esewa.password=Nepal@123
esewa.mpin=1122
esewa.token=123456