spring.application.name=Room-Rental-Service
server.port=7777
spring.datasource.url=jdbc:postgresql://localhost:5432/room_rental_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# MyBatis Configuration
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.bikalp.roomrentalservice.mapper=DEBUG
mybatis.mapper-locations=classpath*:mapper/*.xml
# Validation for images of property
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
# eSewa Test Credentials
esewa.merchant-id=EPAYTEST
esewa.secret-key=8gBm/:&EnhH.1/q
esewa.urls.form=https://rc-epay.esewa.com.np/api/epay/main/v2/form
esewa.urls.status=https://rc.esewa.com.np/api/epay/transaction/status/
esewa.urls.success-callback=https://developer.esewa.com.np/success
esewa.urls.failure-callback=https://developer.esewa.com.np/failure
# default things that are used during dummy payments
esewa.id1=9806800001
esewa.id2=9806800002
esewa.id3=9806800003
esewa.id4=9806800004
esewa.id5=9806800005
esewa.password=Nepal@123
esewa.mpin=1122
esewa.token=123456